### ISSUE TITLE
Questions for Prof and TAs

### ISSUE THREAD

**Issue by Tacitor** [Tacitor/ENGG1420-FinalProj#1]
- [x] The Length Filter takes a "long value _Length_", but then checks to see if a files length is more than 1000 bytes. Clarify what this Filter Processing Elements actually needs to do.

**Comment by Tacitor** [comment]
Do we need to take any security precautions with the credentials for the Laserfiche repository? Do we need to make any secrets or variables in our GitHub repo?
   - Mr. Samad Paydar has said to try and keep the credentials out of the GitHub repo. He suggested to create a configuration file with the credentials, and add the config file to the .gitignore.

**Comment by Tacitor** [comment]
How do we work with local File Entries? Are we given an example folder with a predetermined tree of directories and files?

**Comment by Shalev001** [comment]
what does the print operation print to?

**Comment by Shalev001** [comment]
do we have to use the exact attribute names given?

**Comment by Shalev001** [comment]
do we need to be able to perform recersive proccesing operations on directiries
